### PR TITLE
check queue is not nil before accessing

### PR DESCRIPTION
**Pull request by C-Pro**
I have got a panic in production service.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2157d16]

goroutine 26814443 [running]:
github.com/centrifugal/centrifuge-go.(*cbQueue).pushOrClose(0x0, 0xc0024a4cd8, 0x0)
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/queue.go:64 +0x36
github.com/centrifugal/centrifuge-go.(*cbQueue).push(...)
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/queue.go:55
github.com/centrifugal/centrifuge-go.(*Client).runHandlerSync(0xc001146780, 0xc0024a4cc0)
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/client.go:635 +0xbb
github.com/centrifugal/centrifuge-go.(*Subscription).handlePublication(0xc000814e00, 0xc004855440)
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/subscription.go:590 +0x107
github.com/centrifugal/centrifuge-go.(*Client).handlePush(0xc001146780, 0xc003f4d380)
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/client.go:719 +0x105
github.com/centrifugal/centrifuge-go.(*Client).handle(0xc001146780, 0xc000bd8f00)
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/client.go:682 +0x151
github.com/centrifugal/centrifuge-go.(*Client).readOnce(0xc001146780, {0x2e920e0?, 0xc0012b8cf0?})
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/client.go:618 +0xa9
github.com/centrifugal/centrifuge-go.(*Client).reader(0xc001146780, {0x2e920e0, 0xc0012b8cf0}, 0x1?)
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/client.go:625 +0x5f
created by github.com/centrifugal/centrifuge-go.(*Client).startReconnecting in goroutine 26814431
	/home/runner/go/pkg/mod/github.com/centrifugal/centrifuge-go@v0.10.2/client.go:961 +0x669
```

I suspect the centrifuge connection was closed and `Client.moveToClosed` has set `c.cbQueue` to nil before `Subscription.handlePublication` callback was executed and tried to push to the queue.

So I am adding a check that queue is not nil before calling push. I suspect there should be a better way involving status field, but I am not sure what the lifecycle is supposed to be, so taking most straightforward approach.

### CODE REVIEW

**Comment by FZambia** [comment]
Thanks! I'll take a closer look soon.

Maybe it's possible to build a reproducer using [integration tests](https://github.com/centrifugal/centrifuge-go/blob/master/client_test.go) which are using real Centrifugo instance now:

```
docker run -p 8000:8000 centrifugo/centrifugo:v5 centrifugo --client_insecure
```

I.e. publish to some channel and close the client. I think this should be visible when running a test under [stress](https://pkg.go.dev/golang.org/x/tools/cmd/stress) tool for example. If you will have time to try making it - would be nice, if not - I'll try myself as soon as I start looking.

**Comment by C-Pro** [comment]
> Maybe it's possible to build a reproducer using [integration tests](https://github.com/centrifugal/centrifuge-go/blob/master/client_test.go) which are using real Centrifugo instance now:

Added a test in a separate PR #95  to make it easier to check on both master and this branch.
For me it fails in first couple of runs on master and does not fail in the branch of this pr.
I am running multiple times to catch the race with high confidence:
```
go test -v -count=25 -failfast -timeout=1h -run TestConcurrentPublishSubscribeDisconnect .
```

**Comment by FZambia** [comment]
Many thanks, already started looking whether there is a better way to fix, if won't find a better approach – will proceed with your changes. Hopefully during next several days.

**Comment by FZambia** [comment]
Opened #96, it already includes #95 - it addresses the issue by trying to not calling callbacks at all after close, waiting for currently queued callbacks to fire.

**Pull request closed without merging**
